config/routes.rb
Rails.application.routes.draw do
  get 'admin_leafs/index'
  devise_for :users
  root to: 'pages#home'
  # get '/companies', to: 'pages#companies_index', as: :companies
  # get '/companies/:id', to: 'pages#company_show', as: :company
  # get '/dropoffs', to: 'pages#dropoffs_index', as: :dropoffs
  get '/profile', to: 'pages#profile', as: :profile

  resources :companies, only: [:index, :show]
  
  resources :coupons, only: [:index, :show] do
    resources :baskets, only: [:create]
    # post 'basket', action: :create,  controller: 'baskets', as: 'baskets'
  end
  resources :baskets, only: [:index]
  
  resources :dropoffs, only: [:index]

  resources :leafs, only: [:index, :show, :new, :create, :update]

  resources :admin_leafs, only: [:index, :update]
    


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer bottom-container d-flex justify-content-center pt-3 mt-auto py-3">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="perg-frequentes">
          <div class="perg-fre py-2">
            <h4>Como Podemos Ajudar?</h4>
              <div class="questions">
                <p class="title-footer"><i class="fas fa-angle-right"></i> <%= link_to "Pontos de Coleta LEAFS", root_path %> </p>
                <p class="title-footer"><i class="fas fa-angle-right"></i> <%= link_to "Onde trocar os LEAFS", companies_path %> </p>
              </div>
          </div>
        </div>
      </div>
      <div class="col-md-4 info-cd-fc">
        <p class="title-footer"><i class="fas fa-angle-right"></i> <%= link_to "Cupons de Desconto", coupons_path %> </p>
        <p class="title-footer"><i class="fas fa-angle-right"></i> <%= link_to "Fale Conosco", root_path %> </p>
      </div>
      <div class="col-md-4 mt-2">
        <div class="icons-block">
          <h4>Siga a Leafs nas Redes Sociais</h4>
          <div class="icons">
            <a class="fontawesome" href="#"><i class="fab fa-facebook-square"></i></a>
            <a class="fontawesome" href="#"><i class="fab fa-instagram-square"></i></a>
            <a class="fontawesome" href="#"><i class="fab fa-twitter-square"></i></a>
            <a class="fontawesome" href="#"><i class="fab fa-linkedin"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--BLOCO 2 COM O FOOTER-->
<div>
  <div class="copyright">
    <span>
      Todos os direitos reservados - 2021 - "Leafs - Keep <strong>Green</strong>!"
      <a class="termo" href="#" alt="Termo de Uso">Termo de Uso</a>
      |
      <a class="termo" href="#" alt="Política de Uso">Política de Uso</a>
      -
      Made with <i class="fas fa-heart"></i> at Le Wagon
    </span>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top ">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
    <% end %>
 
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
 
 
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto" style="font-family: 'Noto Sans JP', sans-serif; font-size: 15px;">
      <% if user_signed_in? %>
        <li class="nav-item px-1 mt-3 ">
          <%= link_to "Meus Leafs", leafs_path, class: "nav-link" %>
        </li>
        <li class="nav-item px-1 mt-3">
          <%= link_to "Empresas Parceiras", companies_path, class: "nav-link" %>
        </li>
 
        <!-- <li class="nav-item dropdown"> -->
 
        <li class="nav-item  mt-3">
          <p style="margin-bottom:0;" class='nav-link'>Olá, <%= current_user.username %></p>
        </li>
 
        <!-- Contador leafs aprovados -->
 
        <li class="nav-item mt-4">
          <!-- @user_leafs on application_controller.rb -->
        <% unless current_user.admin %>
          <p style="margin-bottom:0;"><i class="fab fa-envira green"></i><%= link_to "#{current_user.leafs_balance}", leafs_path %></p>
        <% end %>
        </li>
 
        <!-- -------------------------- -->
 
        <li class="nav-item dropdown mt-2">
          <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, crop: :thumb, gravity: :face, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
          <%= image_tag "https://t3.ftcdn.net/jpg/03/46/83/96/360_F_346839683_6nAPzbhpSkIpb8pmAwufkC7c5eD7wYws.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown" style="font-family: 'Noto Sans JP', sans-serif; font-size: 15px0;"> 
            <%= link_to "Cupons", coupons_path, class: "dropdown-item" %>
            <%= link_to "Simular Leafs", "#", class: "dropdown-item" %>
            <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item ">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item ">
          <%= link_to "Empresas Parceiras", companies_path, class: "nav-link" %>
        </li>
 
        <li class="nav-item ">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>