config/routes.rb
Rails.application.routes.draw do
  get 'admin_leafs/index'
  devise_for :users
  root to: 'pages#home'
  # get '/companies', to: 'pages#companies_index', as: :companies
  # get '/companies/:id', to: 'pages#company_show', as: :company
  # get '/dropoffs', to: 'pages#dropoffs_index', as: :dropoffs
  get '/profile', to: 'pages#profile', as: :profile

  resources :companies, only: [:index, :show]
  
  resources :coupons, only: [:index, :show] do
    resources :baskets, only: [:create]
    # post 'basket', action: :create,  controller: 'baskets', as: 'baskets'
  end
  resources :baskets, only: [:index]
  
  resources :dropoffs, only: [:index]

  resources :leafs, only: [:index, :show, :new, :create, :update]

  resources :admin_leafs, only: [:index, :update]
    


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/leaf.rb
class Leaf < ApplicationRecord
  belongs_to :user
  belongs_to :dropoff, optional: true
  has_many :items
  validates :credit, numericality: { only_integer: true }
end

app/controllers/leafs_controller.rb
class LeafsController < ApplicationController
  include LeafCalculator
  skip_before_action :authenticate_user!, only: [:new] 

  def index
    @baskets = current_user.baskets
    @leafs = current_user.leafs.where(accepted: true)
    @balance = (@baskets + @leafs).sort_by { |balance| balance.created_at}
    
    @leafs_pendent = current_user.leafs.where(accepted: false)
    @leaf_pendent_total = 0
    @leafs_pendent.each { |leaf_pendent| @leaf_pendent_total += leaf_pendent.credit }
    @total_user = 0
    @leafs.each do |leaf|
      leaf.items.each do |item|
        @total_user += item.amount
      end
    end
  end
  
  def show
    @leaf = Leaf.find(params[:id])
  end
  
  def new

  end   

  def create
    @leaf = Leaf.new(user: current_user, credit: 0, accepted: false)
    if params[:items][:dropoff].present?
      @dropoff = Dropoff.find(params[:items][:dropoff])
      @leaf.dropoff = @dropoff
    end
    if validate_items(params)
      if @leaf.save
        create_items(@leaf, params[:items])
        @leaf.update(credit:calculate_credit(@leaf))
        redirect_to @leaf, notice: 'Seus leafs serão creditados em sua conta em até 48hrs após confirmação de entrega. Obrigado!'
      else
        render :new
      end
    else
      flash[:notice] = 'Oops, quantidade insuficiente!'
      render :new
    end
  end


  def update
    @leaf = Leaf.find(params[:id])
    @dropoff = Dropoff.find(params[:leaf][:dropoff_id].to_i)
    
    if @leaf.update(dropoff: @dropoff)
      # calculate_leafs
      # balance = @leaf.user.leafs_balance + @leaf.credit
      # @leaf.user.update(leafs_balance: balance)
      redirect_to @leaf, notice: 'Leaf aguardando aprovação.'
    else
      render :show, notice: "Atualização não realizada."
    end
    
  end

  private

  def validate_items(params)
     params[:items][:vidro].to_i > 0 || params[:items][:papel].to_i > 0 || params[:items][:plastico].to_i > 0 || params[:items][:metal].to_i > 0
  end

  def create_items(leaf, params)
    Item.create(leaf: leaf,item_type: 'vidro',  amount: params[:vidro].to_i) if params[:vidro].to_i.positive?
    Item.create(leaf: leaf,item_type: 'papel',  amount: params[:papel].to_i) if params[:papel].to_i.positive?
    Item.create(leaf: leaf,item_type: 'plastico',  amount: params[:plastico].to_i) if params[:plastico].to_i.positive?
    Item.create(leaf: leaf,item_type: 'metal',  amount: params[:metal].to_i) if params[:metal].to_i.positive?
  end

  def calculate_credit(leaf)
    credit = 0
    leaf.items.each do |item|
      credit += (Item::ITEM_TYPE[item.item_type.to_sym]*item.amount)
    end
    credit
  end

end

app/views/leafs/index.html.erb
<!--BANNER DA PÁGINA DO USUÁRIO-->
<div class="banner-index" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.nestle.com/sites/default/files/styles/da_vinci_header_hero_desktop/public/2021-03/csv20-ff6w3z-safeguarding-the-environment.jpg?h=b8626526&itok=yQPv3mQl);">
  <div class="container text-center mt-5">
    <h3 style="font-size: 35px; font-family: 'Roboto Slab', serif; text-decoration: none; color:white;">Você contribuiu reciclando <%= @total_user %> KG de lixo com a Leafs!</h3>
  </div>
</div>
 
<!--Restante do Profile-->
<div class='container'>
  <!--Foto Profile-->
  <div class="mt-4">
    <div class="col-12 col-md-12 col-lg-12 shadow bg-white p-3 mb-2 mr-3" style="background-image: linear-gradient(to right, #F24B4Bee, #F2762Eee, #F24B4Bee);">
      <div class='row align-items-xl-center align-items-lg-center align-items-md-center'>
        <div class="profile-image col-12 col-xl-auto col-lg-auto col-md-12 text-center text-xl-left text-lg-left text-md-center">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, height: 120, width: 120, crop: :thumb, class:"rounded-circle" %>
          <% else %>
            <%= image_tag "https://t3.ftcdn.net/jpg/03/46/83/96/360_F_346839683_6nAPzbhpSkIpb8pmAwufkC7c5eD7wYws.jpg", class: "rounded-circle", size: '100x100' %>
          <% end %>
        </div>
        <!--Profile-->
        <div class="profile-column col-12 col-xl-left col-lg-5 col-md-12 text-center text-xl-left text-lg-left text-md-center">
          <h2><%= current_user.first_name %> <%= current_user.last_name %></h2>
          <div>
            <%= link_to "Gerenciar Conta", edit_user_registration_path(current_user)%>
            <%= link_to "Sair", destroy_user_session_path, method: :delete %>
          </div>
        </div>
        <!--Valor do Saldo-->
        <div class="profile-column col-12 col-xl-auto col-lg-auto col-md-12 ml-xl-5 ml-lg-5 text-center text-xl-right text-lg-right text-md-center">
          <h2> Saldo <i class="fab fa-envira"></i> <%= current_user.leafs_balance %></h2>
          <p class='mb-0 pt-xl-2 pt-lg-2 pt-md-2'> Pendente de Aprovação <i class="fab fa-envira"></i> <%= @leaf_pendent_total %></p>
        </div>
        <div class='col-12 col-xl-auto col-lg-auto col-md-12 mt-lg-0 mt-md-o mt-3 text-center'>
          <%= link_to "Solicitação LEAFS", new_leaf_path, class: "button-green sol-leafs" %>
        </div>
      </div>
    </div>
  </div>
 
    <!--Extrato-->
 
  <div class='row p-3'>
    <div class="extrato-profile col-12 col-md-6 col-lg-7 shadow bg-white pt-lg-4 pt-md-4 pt-3 mb-2 rounded ">
      <h4> Extrato da Conta</h4>
 
      <table class="table table-hover">
        <thead class="profile-head-table">
          <tr class='align-items-center'>
            <th scope="col" class="col-2">Data</th>
            <th scope="col" class="col-8">Operação</th>
            <th scope="col" class="col">Leafs</th>
          </tr>
        </thead>
        <tbody class="profile-body-table">
          <% @balance.each do |item| %>
            <% if item.instance_of?(Leaf) %>
              <tr>
                <td class='success'> <%= item.created_at.strftime('%d/%m/%Y')%> </td>
                <td class='success'> <%= item.dropoff.name if item.dropoff%> </td>
                <td class='success'> + <i class="fab fa-envira"></i> <%= item.credit %> </td>
              </tr>
            <% else %>
              <tr>
                <td class='danger'> <%= item.created_at.strftime('%d/%m/%Y')%> </td>
                <td class='danger'> <%= item.coupon.company.name %> - <%= item.coupon.discount %> </td>
                <td class='danger'> - <i class="fab fa-envira"></i> <%= item.debit %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
 
    <!--Informação LEAFS pendentes-->
    <div class="user-informations col-12 col-md-6 col-lg-5 shadow bg-white p-4 mb-2 rounded ">
      <div class="list-links">
        <h4> </h4>
        
        <!--COLLAPSE UM-->
        <div class="accordion" id="accordionExample">
          <div class="card">
            <div class="card-header dropdown" id="headingOne">
              <h2 class="mb-0" style="font-size: 16px; font-family: 'Noto Sans JP', sans-serif; text-decoration: none;">
                <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne" >
                  <i class="fas fa-angle-right"></i> Meus Leafs Pendentes
                </button>
              </h2>
            </div>
 
            <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
              <div class="card-body">
                <% @leafs_pendent.each do |leaf| %>
                  <div>
                    <%= link_to leaf_path(leaf.id), class:"leaf-p" do %>
                      <p >Solicitação LEAFS: Data - <%= leaf.created_at.strftime('%d/%m/%Y')%> no valor <%= leaf.credit %> LEAFS </p>
                    <% end %>
                  </div>
                <%end%>
              </div>
           </div>
          </div>
 
          <!--COLLAPSE  TWO-->
 
          <div class="card">
            <div class="card-header" style="background-color: linear-gradient(to right, #F24B4B, #F2762E, #F24B4B)" id="headingTwo">
              <h2 class="mb-0" style="font-size: 16px; font-family: 'Noto Sans JP', sans-serif; text-decoration: none">
                <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                  <i class="fas fa-angle-right"></i> Cupons Adquiridos
                </button>
              </h2>
            </div>
 
            <div id="collapseTwo" class="collapse show" aria-labelledby="headingTwo" data-parent="#accordionExample">
              <div class="card-body">
                <% @baskets.each do |basket| %>
                  <div>
                    <%= link_to baskets_path, class:"leaf-p" do %>
                      <p> Cupom <%= basket.coupon.company.name %> - Data: <%= basket.created_at.strftime('%d/%m/%Y') %> no valor de <%= basket.debit %> LEAFS</p>
                    <% end %>
                  </div>
                <%end%>
              </div>
            </div>
          </div>
        </div>
      </div>     
    </div>
 
  </div>
 
</div>

app/views/leafs/new.html.erb
<div class="container d-flex justify-content-center">
    <div class="card-company">
      <div class="form-leaf">
        <h2 class="mt-4 mb-5" style="font-size: 28px; font-family: 'Roboto Slab', serif; text-decoration: none"> Solicitação de LEAFS <i class="fab fa-envira green text-center"></i> </h2>
 
 
        <%= simple_form_for(:items, url: leafs_path, :html => { :class => 'form-horizontal items-form mx-lg-5 mx-md-3', :style => "text-align: left; font-size: 16px; font-family: 'Noto Sans JP', sans-serif; text-decoration: none" }) do |f| %>
          <div class="row">
            <div class="col-lg-6">
              <%= f.input :vidro, label: 'Vidro', as: :integer, placeholder: 'Informe a quantidade em kg' %>
              <%= f.input :papel, label: 'Papel',as: :integer, placeholder: 'Informe a quantidade em kg' %>
            </div>
            <div class="col-lg-6">
              <%= f.input :plastico, label: 'Plástico', as: :integer, placeholder: 'Informe a quantidade em kg'%>
              <%= f.input :metal, label: 'Metal',as: :integer, placeholder: 'Informe a quantidade em kg' %>
            </div>
            <div class="col-lg-6 col-md-6">
            <%= f.input :dropoff, label:'Escolha seu ponto de coleta', collection:Dropoff.order(:name), input_html: { class: 'select2' } %>
            </div>
          </div>
          <%= f.button :submit, "Salvar Leafs", class: 'button-green', style: 'width: 100%'%>
        <% end %>
 
        <div class="table-leafs mt-5 p-4">
          <h4 class="mb-4" style="font-size: 22px; font-family: 'Roboto Slab', serif; text-decoration: none">Tabela de Conversão</h4>
 
          <div class="row">
            <div class="col-12 col-md-6 col-lg-3 mt-sm-2 mt-md-3 mt-lg-1">
              <div class="card recycle" style="background-color: #1eae98;">
                <div class="card-body">
                  <h6 class="card-title title-leaf" style="font-size: 16px; font-family: 'Noto Sans JP', sans-serif; text-decoration: none"><i class="fas fa-recycle"></i> Vidro (Kg)</h6>
                  <p class="card-text leaf-qtdd"> <i class="fab fa-envira green"></i> 2 </p>
                </div>
              </div>
            </div>
 
            <div class="col-12 col-md-6 col-lg-3 mt-2 mt-sm-2 mt-md-3 mt-lg-1">
              <div class="card recycle" style="background-color: #3c8dad;">
                <div class="card-body ">
                  <h6 class="card-title title-leaf" style="font-size: 16px; font-family: 'Noto Sans JP', sans-serif; text-decoration: none"><i class="fas fa-recycle"></i>  Papel (Kg)</h6>
                  <p class="card-text leaf-qtdd"><i class="fab fa-envira green"></i> 1 </p>
                </div>
              </div>
            </div>
 
            <div class="col-12 col-md-6 col-lg-3 mt-2 mt-sm-2 mt-md-3 mt-lg-1">
              <div class="card recycle" style="background-color: #f54748;">
                <div class="card-body">
                  <h6 class="card-title title-leaf" style="font-size: 16px; font-family: 'Noto Sans JP', sans-serif; text-decoration: none"><i class="fas fa-recycle"></i>  Plástico (Kg)</h6>
                  <p class="card-text leaf-qtdd"><i class="fab fa-envira green"></i> 4 </p>
                </div>
              </div>
            </div>
 
            <div class="col-12 col-md-6 col-lg-3 mt-2 mt-sm-2 mt-md-3 mt-lg-1">
              <div class="card recycle" style="background-color: #fb9300;">
                <div class="card-body">
                  <h6 class="card-title title-leaf" style="font-size: 16px; font-family: 'Noto Sans JP', sans-serif; text-decoration: none"><i class="fas fa-recycle"></i> Metal (Kg) </h6>
                  <p class="card-text leaf-qtdd"><i class="fab fa-envira green"></i> 10 </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/leafs/show.html.erb
<div class="container justify-content-center">
  <div class="card-company">
 
    <h2 class="mt-xl-5 mt-lg-5 mt-md-5 mt-sm-4 mt-4 mb-4" style="font-size: 28px; font-family: 'Roboto Slab', serif; text-decoration: none">Solicitação de LEAFS <i class="fab fa-envira green text-center"></i> </h2>
 
    <div class="d-flex justify-content-center">
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col" style="font-size: 18px; font-family: 'Roboto Slab', serif; text-decoration: none"><%= @leaf.accepted ? "Valor Creditado" : "Valor Calculado"  %></th>
            <th scope="col" style="font-size: 18px; font-family: 'Roboto Slab', serif; text-decoration: none">Status</th>
            <th scope="col" style="font-size: 18px; font-family: 'Roboto Slab', serif; text-decoration: none">Ponto de Coleta</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row" style="font-size: 16px; font-family: 'Noto Sans JP', sans-serif; text-decoration: none"><i class="fab fa-envira green mr-1"></i><%= @leaf.credit %></td>
            <td style="font-size: 16px; font-family: 'Noto Sans JP', sans-serif; text-decoration: none"><%= @leaf.accepted ? "Aprovado" : "Pendente"  %></td>
            <td style="font-size: 16px; font-family: 'Noto Sans JP', sans-serif; text-decoration: none"><%= @leaf.dropoff ? @leaf.dropoff.name : "Pendente" %></td>
          </tr>
        </tbody>
      </table>
    </div>
 
    <h4 class="mt-5 mb-3 text-center" style="font-size: 20px; font-family: 'Noto Sans JP', sans-serif; text-decoration: none">A Natureza agradece! Material para reciclagem:</h4>
 
    <ul class="list-group">
      <% @leaf.items.each do |item| %>
        <li class="list-group-item" style="font-size: 16px; font-family: 'Noto Sans JP', sans-serif; text-decoration: none"> <%= "#{item.amount}kg - #{item.item_type}" %> </li>
      <% end %>
    </ul>
 
    <div class="mt-5">
      <%= link_to "Meus Leafs", leafs_path, class: 'button-green mt-4' %>
    </div>
  </div>
</div>