config/routes.rb
Rails.application.routes.draw do
  get 'admin_leafs/index'
  devise_for :users
  root to: 'pages#home'
  # get '/companies', to: 'pages#companies_index', as: :companies
  # get '/companies/:id', to: 'pages#company_show', as: :company
  # get '/dropoffs', to: 'pages#dropoffs_index', as: :dropoffs
  get '/profile', to: 'pages#profile', as: :profile

  resources :companies, only: [:index, :show]
  
  resources :coupons, only: [:index, :show] do
    resources :baskets, only: [:create]
    # post 'basket', action: :create,  controller: 'baskets', as: 'baskets'
  end
  resources :baskets, only: [:index]
  
  resources :dropoffs, only: [:index]

  resources :leafs, only: [:index, :show, :new, :create, :update]

  resources :admin_leafs, only: [:index, :update]
    


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :coupons
  validates :name, :url, :logo, presence: true
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
    @coupons = Coupon.where(company_id: params[:id])
  end
end

app/views/companies/index.html.erb
<!--BANNER DIFERENTE QUANDO USER-->
<% if user_signed_in? %>
  <div class="banner-index" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.nestle.com/sites/default/files/styles/da_vinci_header_hero_desktop/public/2021-03/csv20-ff6w3z-safeguarding-the-environment.jpg?h=b8626526&itok=yQPv3mQl);">
    <div class="container text-center mt-5">
      <h2 style="font-size: 35px; font-family: 'Roboto Slab', serif; text-decoration: none; color:white;"> Bem-Vindo!</h2> <!--AJUSTAR A MENSAGEM DO BANNER PARA QUANDO LOGADO-->
      <p style="font-weight: bold"> Preservar o meio ambiente é agir no presente para proteger o futuro. Já reciclou o seu lixo hoje?</p>
    </div>
  </div>
<% else %>
  <div class="banner-index" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.nestle.com/sites/default/files/styles/da_vinci_header_hero_desktop/public/2021-03/csv20-ff6w3z-safeguarding-the-environment.jpg?h=b8626526&itok=yQPv3mQl);">
    <div class="container text-center mt-5">
      <h2 style="font-size: 40px; font-family: 'Roboto Slab', serif; text-decoration: none; color:white; line-heigth: 1.6;"> Faça parte dessa mudança!</h2>
      <p style="font-weight: bold"> A preservação do meio ambiente começa com pequenas atitudes diárias! </p>
      <br>
      <%= link_to 'Cadastre-se', new_user_registration_path, class: 'button-orange' %>
    </div>
  </div>
<% end %>
 
<div class='container mt-4 mt-xl-5 mt-lg-5 mt-md-5 mt-sm-4'>
  <div class="row justify-content-center justify-content-xl-start justify-content-lg-start justify-content-md-center justify-content-sm-center mb-xl-5 mb-lg-5 mb-md-12 mb-sm-3 mb-4">
    <div class="col-12 col-xl-3 col-lg-3 col-md-4 col-sm-6 mb-3 mb-xl-0 mb-lg-0 text-center text-xl-left text-lg-left">
      <%= link_to 'Ver todos os cupons', coupons_path, class:'button-green'%>
    </div>
    <div class="col-12 col-xl-6 col-lg-6 col-md-12 col-sm-6 text-center">
      <h2 class='align-content-center'  style="font-size: 28px; font-family: 'Roboto Slab', serif; text-decoration: none;">Empresas Parceiras - Compras Online</h2>
    </div>
  </div>
  <div class='row'>
    <% @companies.each do |company| %>
      <div class="col-lg-3 col-md-6 col-sm-6 mb-4">
        <div class="card-companies">
          <%= link_to company_path(company) do %>
            <%= image_tag "#{company.logo}", size: "160x96", class: 'mb-2' %>
            <br>
            <%= link_to 'Cupons', company_path(company), class: 'button-green', target: "_blank" %>
          <% end %>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/companies/show.html.erb
<% if user_signed_in? %>
  <div class="banner-index" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.nestle.com/sites/default/files/styles/da_vinci_header_hero_desktop/public/2021-03/csv20-ff6w3z-safeguarding-the-environment.jpg?h=b8626526&itok=yQPv3mQl);">
    <div class="container text-center mt-5">
      <h2 style="font-size: 35px; font-family: 'Roboto Slab', serif; text-decoration: none; color:white;"> 
      Bem-Vindo!
      </h2>
      <p style="font-weight: bold"> Preservar o meio ambiente é agir no presente para proteger o futuro. Já reciclou o seu lixo hoje?</p>
    </div>
  </div>
<% else %>
  <div class="banner-index" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.nestle.com/sites/default/files/styles/da_vinci_header_hero_desktop/public/2021-03/csv20-ff6w3z-safeguarding-the-environment.jpg?h=b8626526&itok=yQPv3mQl);">
    <div class="container text-center mt-5">
      <h2 style="font-size: 40px; font-family: 'Roboto Slab', serif; text-decoration: none; color:white; line-heigth: 1.6;"> Faça parte dessa mudança!
      </h2>
        <p style="font-weight: bold"> A preservação do meio ambiente começa com pequenas atitudes diárias! </p>
      <br>
      <%= link_to 'Cadastre-se', new_user_registration_path, class: 'button-orange' %>
    </div>
  </div>
<% end %>


<div class="container">
  <div class="card-company mt-5">
    <%= link_to @company.url, target: "_blank" do %>
      <%= image_tag "#{@company.logo}", size: "213x128", style: "border: 1px solid #cacaca;", class: "my-3" %>
    <% end %>
    <div class="d-flex justify-content-center mb-3">
      <table class="content-table">
        <thead>
            <tr>
            </tr>
        </thead>
        <% @coupons.each do |coupon| %>
        <tbody>
          <tr>
            <td  style="font-size: 18px; font-family: 'Noto Sans JP', sans-serif; text-decoration: none"><i class="fas fa-ticket-alt mr-4"></i><span class="mb-5"><%= coupon.discount %></span></td>
            <td ><%= link_to "Adquirir", coupon_baskets_path(coupon.id), method: :create, data:{confirm: "Tem certeza? Valor: #{coupon.leafs_value} leafs"}, class: 'button-transparent ml-2 h6', target: "_blank" %></td>
          </tr>
        </tbody>
        <%end%>
      </table>
    </div>
    <%= link_to "#{@company.name}", @company.url, class: 'button-green', target: "_blank" %>
  </div>
</div>